name: Format R

on:
  push:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.0'
      - name: Install styler
        run: Rscript -e 'install.packages("styler")'
      - name: Format R files
        run: |
          Rscript -e 'library(styler); style_dir(path = ".", filetype = "r")'
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Format R files"
